export const GET_REVIEWS_PENDING="GET_REVIEWS_PENDING";
export const GET_REVIEWS_SUCCESS="GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_ERROR="GET_REVIEWS_ERROR";
export const UPDATE_REVIEWS = "UPDATE_REVIEWS";
